// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOPtZnnEI9ld8L1zC6aDvWl-JWviiLepY',
    appId: '1:159836513479:web:2c94a42ababac2671b8ae2',
    messagingSenderId: '159836513479',
    projectId: 'notesapp-f020e',
    authDomain: 'notesapp-f020e.firebaseapp.com',
    storageBucket: 'notesapp-f020e.firebasestorage.app',
    measurementId: 'G-KTYTZPXDTN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS4UQyLnJ67HoRLX9SoQgCQlhDKByT8nI',
    appId: '1:159836513479:android:23a9bb50275b28681b8ae2',
    messagingSenderId: '159836513479',
    projectId: 'notesapp-f020e',
    storageBucket: 'notesapp-f020e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwL11POM72YCpKp2iGsX0Sa4efVCNm4jo',
    appId: '1:159836513479:ios:53d6e03560d501691b8ae2',
    messagingSenderId: '159836513479',
    projectId: 'notesapp-f020e',
    storageBucket: 'notesapp-f020e.firebasestorage.app',
    iosBundleId: 'com.example.notesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwL11POM72YCpKp2iGsX0Sa4efVCNm4jo',
    appId: '1:159836513479:ios:53d6e03560d501691b8ae2',
    messagingSenderId: '159836513479',
    projectId: 'notesapp-f020e',
    storageBucket: 'notesapp-f020e.firebasestorage.app',
    iosBundleId: 'com.example.notesapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOPtZnnEI9ld8L1zC6aDvWl-JWviiLepY',
    appId: '1:159836513479:web:ecc39c8258246e311b8ae2',
    messagingSenderId: '159836513479',
    projectId: 'notesapp-f020e',
    authDomain: 'notesapp-f020e.firebaseapp.com',
    storageBucket: 'notesapp-f020e.firebasestorage.app',
    measurementId: 'G-T5KM8BKFB9',
  );
}
